services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:local_password@db:5432/nova?schema=public
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env.development
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
